# -*- coding: utf-8 -*-
"""sort_object_y.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-YCLWnKrmwka9Wyds_wBVH0V8rlM0yvj
"""

obj_detected = {'bottle': [110, 30], 'glass': [60, 35], 'book': [310, 23], 'phone': [90, 33], 'pen': [155, 100], 'mouse':
[200, 45], 'remote': [298, 165], 'fan': [300, 36]}

obj_detected.items()

from typing import ValuesView
sort_object = sorted(obj_detected.items(), key=lambda x:x[0] , reverse=False)
sort_object